#pragma comment(linker,"/export:#36=ntdll.#36,@36,NONAME")
#pragma comment(linker,"/export:HeapAlloc=ntdll.RtlAllocateHeap")
#pragma comment(linker,"/export:ImAGayFunction=Proxy.ImAGayFunction")
#pragma comment(linker,"/export:Lmao=Proxy.Lmao,DATA")
#pragma comment(linker,"/export:#234=ntdll.#234,@234,NONAME")
#pragma comment(linker,"/export:#456=ntdll.#456,@456,NONAME")
